name: monitor_habitos
description: Um aplicativo para monitorar hábitos diários, semanais e mensais.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  android_alarm_manager_plus: ^4.0.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_riverpod: ^2.0.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
